---
# 运行样例：ansible-playbook /opt/auto-deployment/setup_cdh_cluster/ansible/deploy_cdh.yml
# author: Jesse.liu
# date: 2020-07-18
# function: 自动部署 mysql server & client
# CDH 官方 mysql 安装指南：https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/cm_ig_mysql.html

  - name: 卸载可能与 mysql 冲突的包
    yum:
      name: '{{item}}'
      state: absent
    loop:
      - 'mariadb-libs'

#  - name: 安装 mysql 及其依赖
#    yum:
#      name: '{{paths.package}}/{{item}}'
#      state: present
#    loop:
#      - 'mysql-community-common-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-libs-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-libs-compat-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-devel-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-embedded-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-embedded-compat-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-embedded-devel-5.7.30-1.el7.x86_64.rpm'
#      - 'mysql-community-client-5.7.30-1.el7.x86_64.rpm'

